# Generated by Django 4.2.3 on 2023-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_userpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="500",
                null=True,
                upload_to="media/images",
                width_field="500",
            ),
        ),
    ]
